#!/bin/sh -e

if [ x"$1" != "xconfigure" ]; then
    exit 0
fi

# chown
echo -n "chmod root dir ... " 
chown -R root:root    	 /opt/${GROUP}/bin
chown -R root:root    	 /opt/${GROUP}/debian
echo " .done"

# chmod
echo -n "chmod 755 bin/*.sh ... " 
chmod 755 /opt/${GROUP}/bin/*.sh
echo " .done"

echo "finish."
